version: '3'

services:
  # app:
    # build:
    #   dockerfile: Dockerfile
    #   context: .
    #   target: dev
    # volumes:
    #   - .:/app
    # ports:
    #   - 8080:8080
    # environment: 
    #   - DATABASE_HOST=${DATABASE_HOST}
    #   - DATABASE_USER=${DATABASE_USER}
    #   - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    #   - DATABASE_NAME=${DATABASE_NAME}
    #   - ENV=${ENV}
    #   - JWT_SECRET=${JWT_SECRET}
    # depends_on:
    #   - postgres  
    # command: go run main.go
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data      
  pgadmin-compose:
    image: dpage/pgadmin4:6.14
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgres    
